CREATE DATABASE QLBanSach;

USE QLBanSach;

CREATE TABLE KhachHang(
	MaKH INT AUTO_INCREMENT,
	TaiKhoan VARCHAR(100),
	MatKhau VARCHAR(100),
	Email VARCHAR(200),
	DiaChi VARCHAR(100),
	DienThoai VARCHAR(11),
	GioiTinh VARCHAR(4),
	NgaySinh DATETIME,
	HoTen VARCHAR(200),
	PRIMARY KEY(MaKH)
);

CREATE TABLE NhaXuatBan(
	MaNXB INT AUTO_INCREMENT,
	TenNSB VARCHAR(200),
	DiaChi VARCHAR(100),
	DienThoai VARCHAR(11),
	MaSach INT,
	PRIMARY KEY(MaNXB)
);

CREATE TABLE ChuDe(
	MaChuDe INT AUTO_INCREMENT,
	TenChuDe VARCHAR(100),
	MaSach INT,
	PRIMARY KEY(MaChuDe)
);

CREATE TABLE DonHang(
	MaDonHang INT AUTO_INCREMENT,
	DaThanhToan BIT,
	NgayGiao DATETIME,
	NgayDat DATETIME,
	TinhTrangGH VARCHAR(50),
	MaKhachHang INT,
	PRIMARY KEY(MaDonHang),
	CONSTRAINT FK_MaKhachHang_DonHang FOREIGN KEY(MaKhachHang) REFERENCES KhachHang(MaKH)
);

CREATE TABLE TacGia(
	MaTacGia INT AUTO_INCREMENT,
	TenTacGia VARCHAR(200),
	DiaChi VARCHAR(100),
	TieuSu TEXT,
	DienThoai VARCHAR(11),
	PRIMARY KEY(MaTacGia)
);

CREATE TABLE Sach(
	MaSach INT AUTO_INCREMENT,
	TenSach VARCHAR(200),
	GiaBan INT,
	MoTa TEXT,
	AnhBia BLOB,
	NgayCapNhat DATETIME,
	LuongTon INT,
	MaChuDe INT,
	MaNXB INT,
	PRIMARY KEY(MaSach),
	CONSTRAINT FK_MaChuDe_Sach FOREIGN KEY(MaChuDe) REFERENCES Chude(MaChuDe),
	CONSTRAINT FK_MaNXB_Sach FOREIGN KEY(MaNXB) REFERENCES NhaXuatBan(MaNXB)
);

CREATE TABLE DonHang_Sach (
    MaDonHang INT,
    MaSach INT,
    SoLuong INT,
    DonGia INT,
    PRIMARY KEY (MaDonHang, MaSach),
    CONSTRAINT FK_MaDonHang_Donhang_Sach FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaDonHang),
    CONSTRAINT FK_MaSach_Donhang_Sach FOREIGN KEY (MaSach) REFERENCES Sach(MaSach)
);

CREATE TABLE TacGia_Sach (
    MaTacGia INT,
    MaSach INT,
    VaiTro VARCHAR(255),
    ViTri VARCHAR(255),
    PRIMARY KEY (MaTacGia, MaSach),
    CONSTRAINT FK_MaTacGia_TacGia_Sach FOREIGN KEY (MaTacGia) REFERENCES TacGia(MaTacGia),
    CONSTRAINT FK_MaSach_TacGia_Sach FOREIGN KEY (MaSach) REFERENCES Sach(MaSach)
);